# Generated by Django 6.0.1 on 2026-01-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField(help_text='Basic wind speed in m/s')),
                ('seismic_zone', models.CharField(max_length=10)),
                ('zone_factor', models.FloatField()),
                ('max_temp', models.FloatField(help_text='Maximum shade air temperature in °C')),
                ('min_temp', models.FloatField(help_text='Minimum shade air temperature in °C')),
            ],
            options={
                'ordering': ['state', 'district'],
                'unique_together': {('state', 'district')},
            },
        ),
        migrations.CreateModel(
            name='BridgeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(choices=[('Highway', 'Highway'), ('Other', 'Other')], default='Highway', max_length=20)),
                ('span', models.FloatField(help_text='Span in meters')),
                ('carriageway_width', models.FloatField(help_text='Carriageway width in meters')),
                ('footpath', models.CharField(choices=[('none', 'None'), ('single', 'Single-sided'), ('both', 'Both')], default='none', max_length=10)),
                ('skew_angle', models.FloatField(default=0, help_text='Skew angle in degrees')),
                ('girder_grade', models.CharField(default='E250', max_length=10)),
                ('cross_bracing_grade', models.CharField(default='E250', max_length=10)),
                ('deck_grade', models.CharField(default='M25', max_length=10)),
                ('girder_spacing', models.FloatField(blank=True, null=True)),
                ('num_girders', models.IntegerField(blank=True, null=True)),
                ('deck_overhang', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge_design.locationdata')),
            ],
        ),
    ]
