# Generated by Django 6.0.1 on 2026-01-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridgedesign',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='bridgedesign',
            name='description',
            field=models.TextField(blank=True, help_text='Design description or notes', null=True),
        ),
        migrations.AddField(
            model_name='bridgedesign',
            name='estimated_cost',
            field=models.FloatField(blank=True, help_text='Estimated cost in lakhs', null=True),
        ),
        migrations.AddField(
            model_name='bridgedesign',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bridgedesign',
            name='name',
            field=models.CharField(default='Untitled Design', help_text='Design name/identifier', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bridgedesign',
            name='overall_width',
            field=models.FloatField(blank=True, help_text='Calculated overall bridge width', null=True),
        ),
        migrations.AddField(
            model_name='bridgedesign',
            name='total_weight',
            field=models.FloatField(blank=True, help_text='Estimated total weight in tons', null=True),
        ),
    ]
